name: teslapp
services:
  webapp:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./docker/nginx.${ENVIRONMENT:-local}.conf:/etc/nginx/nginx.conf:ro,z
    networks:
      shared:
        ipv4_address: 172.22.0.11
    develop:
      watch:
        - action: sync
          path: ./www/_assets
          target: /var/www/html/_assets
        - action: sync+restart
          path: ./www
          target: /var/www/html
          ignore:
            - _assets/
        - action: sync
          path: ./private
          target: /var/www/private
        - action: rebuild
          path: composer.json
        - action: rebuild
          path: composer.lock
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: docker/

networks:
  shared:
    name: teslapp_shared
    external: false
    ipam:
      config:
        - subnet: 172.22.0.0/16
