# Production environment override — runs on Kárkharos, external network
name: teslapp-prod
services:
  webapp:
    restart: always
    ports:
      - '50025:80'
    networks:
      shared:
        ipv4_address: 172.22.0.10

networks:
  shared:
    name: teslapp_shared
    external: true
