# Production environment override — runs on Kárkharos, external network
name: teslapp
services:
  webapp:
    container_name: app-prod
    restart: always
    networks:
      shared:
        ipv4_address: 172.22.0.10

networks:
  shared:
    name: teslapp_shared
    external: true
