# Production environment override — runs on Kárkharos, external network
name: teslapp-prod
services:
  webapp:
    restart: always
    networks:
      shared:
        ipv4_address: 172.22.0.10

networks:
  shared:
    external: true
