name: teslapp
services:
  webapp:
    build: .
    ports:
      - '50025:80'
    env_file: .env
    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    name: teslapp_shared
    external: true
