name: Deploy to Kárkharos
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write .env
        run: echo '${{ secrets.WEBAPP_ENV }}' > $GITHUB_WORKSPACE/.env

      - name: Deploy webapp
        run: |
          cd $GITHUB_WORKSPACE
          docker compose up -d --build --force-recreate webapp
