name: Deploy to Kárkharos
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to target directory
        run: rsync -a --delete $GITHUB_WORKSPACE/ /home/feyli/iut/teslapp/webapp/

      - name: Write .env
        run: echo '${{ secrets.WEBAPP_ENV }}' > /home/feyli/iut/teslapp/webapp/.env

      - name: Deploy webapp
        run: |
          cd /home/feyli/iut/teslapp
          docker compose up -d --build --force-recreate webapp
